#include "governance.hpp"
#include "system_state.hpp"
#include "actors/ownership.hpp"
namespace governance {
namespace {
dcon::authority_grant_id find_institution_grant(sys::state const& s,dcon::institution_id h,authority_kind k,dcon::nation_id n,dcon::territorial_unit_id t){dcon::authority_grant_id result{};s.world.institution_for_each_authority_grant_institution_holder_as_institution(h,[&](dcon::authority_grant_institution_holder_id r){auto g=s.world.authority_grant_institution_holder_get_authority_grant(r);if(s.world.authority_grant_get_kind(g)==uint8_t(k)&&((n&&s.world.authority_grant_get_nation_from_authority_grant_nation_scope(g)==n)||(t&&s.world.authority_grant_get_territorial_unit_from_authority_grant_territorial_scope(g)==t)))result=g;});return result;}
dcon::authority_grant_id find_office_grant(sys::state const& s,dcon::office_id h,authority_kind k,dcon::nation_id n,dcon::territorial_unit_id t){dcon::authority_grant_id result{};s.world.office_for_each_authority_grant_office_holder_as_office(h,[&](dcon::authority_grant_office_holder_id r){auto g=s.world.authority_grant_office_holder_get_authority_grant(r);if(s.world.authority_grant_get_kind(g)==uint8_t(k)&&((n&&s.world.authority_grant_get_nation_from_authority_grant_nation_scope(g)==n)||(t&&s.world.authority_grant_get_territorial_unit_from_authority_grant_territorial_scope(g)==t)))result=g;});return result;}
}
dcon::institution_id create_institution(sys::state& s,dcon::nation_id n,institution_kind k){if(!n)return{};auto i=s.world.create_institution();s.world.institution_set_kind(i,uint8_t(k));s.world.force_create_institution_nation(i,n);auto a=s.world.create_economic_actor();s.world.economic_actor_set_kind(a,uint8_t(actors::ownership::actor_kind::state_entity));s.world.force_create_institution_actor(i,a);return i;}
dcon::economic_actor_id actor_for_institution(sys::state const& s,dcon::institution_id i){return i?s.world.institution_get_economic_actor_from_institution_actor(i):dcon::economic_actor_id{};}
dcon::nation_id nation_of(sys::state const& s,dcon::institution_id i){return i?s.world.institution_get_nation_from_institution_nation(i):dcon::nation_id{};}
std::vector<dcon::institution_id> institutions_of(sys::state const& s,dcon::nation_id n){std::vector<dcon::institution_id> v;s.world.nation_for_each_institution_nation_as_nation(n,[&](dcon::institution_nation_id r){v.push_back(s.world.institution_nation_get_institution(r));});return v;}
dcon::office_id create_office(sys::state& s,dcon::institution_id i,office_kind k){if(!i)return{};auto o=s.world.create_office();s.world.office_set_kind(o,uint8_t(k));s.world.force_create_office_institution(o,i);return o;}
dcon::institution_id institution_for_office(sys::state const& s,dcon::office_id o){return o?s.world.office_get_institution_from_office_institution(o):dcon::institution_id{};}
bool set_parent(sys::state& s,dcon::institution_id c,dcon::institution_id p){if(!c||!p||c==p||nation_of(s,c)!=nation_of(s,p))return false;if(parent_of(s,c)==p)return true;for(auto x=p;x;x=parent_of(s,x))if(x==c)return false;if(auto old= s.world.institution_get_institution_parent_as_child(c))s.world.delete_institution_parent(old);s.world.force_create_institution_parent(c,p);return true;}
dcon::institution_id parent_of(sys::state const& s,dcon::institution_id c){if(!c)return{};auto r=s.world.institution_get_institution_parent_as_child(c);return r?s.world.institution_parent_get_parent(r):dcon::institution_id{};}
std::vector<dcon::institution_id> children_of(sys::state const& s,dcon::institution_id p){std::vector<dcon::institution_id>v;s.world.institution_for_each_institution_parent_as_parent(p,[&](dcon::institution_parent_id r){v.push_back(s.world.institution_parent_get_child(r));});return v;}
template<class H,class S>dcon::authority_grant_id create_grant(sys::state& s,H h,authority_kind k,S scope){dcon::nation_id n{};dcon::territorial_unit_id t{};if constexpr(std::is_same_v<S,dcon::nation_id>)n=scope;else t=scope;if(!h||(!n&&!t))return{};if constexpr(std::is_same_v<S,dcon::nation_id>){auto holder_nation=[&](){if constexpr(std::is_same_v<H,dcon::institution_id>)return nation_of(s,h);else return nation_of(s,institution_for_office(s,h));};if(holder_nation()!=n)return{};}auto existing=[&](){if constexpr(std::is_same_v<H,dcon::institution_id>)return find_institution_grant(s,h,k,n,t);else return find_office_grant(s,h,k,n,t);};if(auto g=existing())return g;auto g=s.world.create_authority_grant();s.world.authority_grant_set_kind(g,uint8_t(k));if constexpr(std::is_same_v<H,dcon::institution_id>)s.world.force_create_authority_grant_institution_holder(g,h);else s.world.force_create_authority_grant_office_holder(g,h);if(n)s.world.force_create_authority_grant_nation_scope(g,n);else s.world.force_create_authority_grant_territorial_scope(g,t);return g;}
dcon::authority_grant_id grant_authority_to_institution(sys::state&s,dcon::institution_id h,authority_kind k,dcon::nation_id n){return create_grant(s,h,k,n);}dcon::authority_grant_id grant_authority_to_institution(sys::state&s,dcon::institution_id h,authority_kind k,dcon::territorial_unit_id t){return create_grant(s,h,k,t);}dcon::authority_grant_id grant_authority_to_office(sys::state&s,dcon::office_id h,authority_kind k,dcon::nation_id n){return create_grant(s,h,k,n);}dcon::authority_grant_id grant_authority_to_office(sys::state&s,dcon::office_id h,authority_kind k,dcon::territorial_unit_id t){return create_grant(s,h,k,t);}
bool revoke_authority(sys::state&s,dcon::authority_grant_id g){if(!g)return false;s.world.delete_authority_grant(g);return true;}bool has_authority(sys::state const&s,dcon::institution_id h,authority_kind k,dcon::nation_id n){return bool(find_institution_grant(s,h,k,n,{}));}bool has_authority(sys::state const&s,dcon::institution_id h,authority_kind k,dcon::territorial_unit_id t){return bool(find_institution_grant(s,h,k,{},t));}bool has_authority(sys::state const&s,dcon::office_id h,authority_kind k,dcon::nation_id n){return bool(find_office_grant(s,h,k,n,{}));}bool has_authority(sys::state const&s,dcon::office_id h,authority_kind k,dcon::territorial_unit_id t){return bool(find_office_grant(s,h,k,{},t));}
dcon::institution_id central_government_for(sys::state&s,dcon::nation_id n){for(auto i:institutions_of(s,n))if(s.world.institution_get_kind(i)==uint8_t(institution_kind::central_government))return i;return create_institution(s,n,institution_kind::central_government);}
bool bind_local_government(sys::state&s,dcon::local_government_id l,dcon::institution_id i){if(!l||!i||!nation_of(s,i))return false;auto current=s.world.local_government_get_institution_from_local_government_institution(l);if(current)return current==i;s.world.force_create_local_government_institution(l,i);return true;}
void bootstrap(sys::state&s){s.world.for_each_nation([&](dcon::nation_id n){central_government_for(s,n);});}
}
