#include "test_support.hpp"

#include "rural_economy_tests.cpp"
#include "capital_income_tests.cpp"
#include "deposit_payments_tests.cpp"
#include "capital_allocation_tests.cpp"
#include "capital_regulation_tests.cpp"
#include "monetary_policy_tests.cpp"
#include "constitution_tests.cpp"
#include "politics_tests.cpp"
