#include "test_support.hpp"

#include "legacy_consumer_purge_tests.cpp"
#include "commodity_logistics_tests.cpp"
#include "investment_ranking_tests.cpp"
#include "market_access_tests.cpp"
#include "cargo_transit_tests.cpp"
#include "spatial_runtime_tests.cpp"
#include "actor_market_tests.cpp"
#include "canonical_routed_shipments_tests.cpp"
#include "human_development_tests.cpp"
#include "world_trade_capacity_tests.cpp"
#include "simulation_runner_tests.cpp"
#include "diplomatic_crisis_dynamics_tests.cpp"
#include "ve_scalar_backend_tests.cpp"
